import { test, expect } from '@playwright/test';

test.describe('Forum E2E', () => {
  // Use a unique title to avoid collisions
  const uniqueTitle = `Automated E2E Topic ${Date.now()}`;

  test('User can log in and create a new forum topic', async ({ page }) => {
    // 1. Go to sign-in page
    await page.goto('/auth/signin');

    // 2. Log in using the dummy account provisioned in auth.ts
    await page.fill('input[name="identifier"]', 'dummy@example.com');
    await page.fill('input[name="password"]', 'password123');
    await page.click('button:has-text("Sign In")');

    // 3. Wait for redirect to home
    await expect(page).toHaveURL('/');
    
    // 4. Click the "+ New Topic" button in the Sidebar
    await page.click('text="+ New Topic"');
    await expect(page).toHaveURL('/forum/create');

    // 5. Fill out the forum creation form
    await page.fill('input[placeholder="What do you want to talk about?"]', uniqueTitle);
    
    // The description uses Tiptap rich text editor which might be contenteditable
    await page.locator('.ProseMirror').fill('This is a test description generated by Playwright E2E automation.');
    
    // Add a tag
    await page.fill('input[placeholder="e.g. React, Next.js, Help"]', 'E2ETesting');

    // 6. Submit the form
    await page.click('button:has-text("Post Discussion")');

    // 7. Verify we are redirected to the home page or forum page and the topic is visible
    await expect(page).toHaveURL(new RegExp('/forum/.*|/'));
    
    // Verify the title appears on the page
    await expect(page.locator(`text="${uniqueTitle}"`).first()).toBeVisible({ timeout: 10000 });
  });
});
